### ISSUE TITLE
Remove unused code. 

### ISSUE THREAD

**Issue by bhavikpatel3234** [virenshah1111/MySpringProject#2]
https://github.com/virenshah1111/MySpringProject/blob/b0961894cb32c5a73097ebb7909164cd06c1b2b6/src/main/java/com/config/SpringSecurityInitializer.java#L12

**Comment by virenshah1111** [comment]
Hello @bhavikpatel3234 

In Spring, security is implemented using DelegatingFilterProxy. To register it, with spring container in Java configuration,we should use AbstractSecurityWebApplicationInitializer.

The spring will detect the instance of this class during application startup, and register the DelegatingFilterProxy to use the springSecurityFilterChain before any other registered Filter.
